image: mcr.microsoft.com/playwright:v1.29.0-focal 

stages:
  - lint
  - test

lint:
  stage: lint
  cache:
    key: npm
    paths:
      - node_modules
  script:
    - npm install
    - npm run lint

test:
  stage: test
  cache:
    key: npm
    paths:
      - node_modules
  script:
    - npm install
    - npm run test